events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format soc_json escape=json
        '{'
        '"timestamp":"$time_iso8601",'
        '"source_ip":"$remote_addr",'
        '"method":"$request_method",'
        '"request_uri":"$request_uri",'
        '"status":$status,'
        '"bytes_sent":$body_bytes_sent,'
        '"user_agent":"$http_user_agent",'
        '"request_time":$request_time'
        '}';

    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name _;

        root /usr/share/nginx/html;
        index index.html;

        access_log /var/log/nginx/access.json soc_json;
        error_log /var/log/nginx/error.log warn;

        location = /health {
            access_log off;
            default_type text/plain;
            return 200 "ok\n";
        }

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
